# Generated by Django 6.0.7 on 2026-07-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('education', models.TextField()),
                ('profile_images', models.ImageField(blank=True, null=True, upload_to='profile/')),
            ],
        ),
    ]
