# Generated by Django 6.0.7 on 2026-07-30 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_images',
            new_name='profile_image',
        ),
    ]
